ronivay/XenOrchestraInstallerUpdater

- xo-install.sh
> Correct LOGFILE typo

- xo-install.sh
I Was Having Problems Installing And I Wanted To Get The Latest Release (Tag).
> Added Support For Specifying A Tag To Install

- README.md
- xo-install.sh
Hello,
I made a few changes to the script so that it will also work in Ubuntu 20. I have tested this on Ubuntu 20.04 on an x86 VM, and again on a Raspberry Pi 4 running Ubuntu 20.04 ARM.
The only real difference between 16/18 and 20 is the python-minimal package was renamed to python2-minimal.
> Fix for ubuntu 20

- sample.xo-install.cfg
- xo-install.sh
Hi,
I really like this script, but I'm using custom Xen Orchestra repository that removes premium features from sidebar. I though that adding option to set custom Xen Orchestra repository would be good idea.
> Add support for custom Xen Orchestra repository

- xo-install.sh
Fix freezing on checking for universe.
> Fix universe check on Ubuntu

- .editorconfig
- README.md
- sample.xo-install.cfg
- xo-install.sh
- xo-vm-import.sh
Implement experimental support for backup proxy installation. Requested in https://github.com/ronivay/XenOrchestraInstallerUpdater/issues/104
There is no official documentation describing the installation procedure so implemented method is outcome of trial and error, but works.
> Add backup proxy installation

- README.md
- sample.xo-install.cfg
- xo-install.sh
Original: https://github.com/ronivay/XenOrchestraInstallerUpdater/pull/112
Merged the options into a single one.
> Adding option to disable repos installation

- README.md
- xo-install.sh
> feat: use python3 for all OS's

- README.md
- xo-install.sh
> feat: drop support for EOL OS's

- sample.xo-install.cfg
- xo-install.sh
> feat: add config option for remote syslog

- README.md
- xo-install.sh
> fix: install dmidecode package if missing

- xo-install.sh
> fix: add missing findmnt command to sudoers configuration

- xo-install.sh
> fix: do not run chown recursively to mounts dir with non-root user

- README.md
remove branch query param as these are only ran in PR's
> fix: github actions badges in README

- xo-install.sh
related to: https://github.com/ronivay/XenOrchestraInstallerUpdater/issues/200
fixes the deb part
> fix: replace deprecated nodesource repository installation

- xo-install.sh
Reverts ronivay/XenOrchestraInstallerUpdater#201
related to https://github.com/ronivay/XenOrchestraInstallerUpdater/issues/200
> Revert "fix: replace deprecated nodesource repository installation"

- README.md
- xo-install.sh
> fix: add patch pkg to dependencies

- xo-install.sh
> fix: match to only running node process named xo-server

- README.md
- sample.xo-install.cfg
- xo-install.sh
* Add new configuration option `PROXY_PORT` with default value of 443
* Modify port in proxy configuration if port is something else than default 443
* Add mention to README that proxy address needs to be modified in XO side if using something else than default
fixes #235
> feat: add possibility to change proxy listening port

- sample.xo-install.cfg
- xo-install.sh
* add new `LISTEN_ADDRESS` configuration option
* if config option not defined, let XO use it's default listen address method
resolves #269
> feat: add possibility to use custom listen address in XO config

- xo-install.sh
bug introduced by: https://github.com/ronivay/XenOrchestraInstallerUpdater/pull/274 and missed during review
> fix: move libvhdi-tools install inside correct if statement
