xo-install.sh
PR addresses a couple of issues.
1. Using `id -u` is preferable to using `whoami` for detecting root. The root user doesn't have to be named root but must be uid 0.
2. Use $INSTALLDIR/xo-server for working directory in systemd service file.
=> A couple of small fixes

README.md
The File Name For The Install Script In The README.md Is Incorrect and Had Been Updated So it Is Correct.
=> Fixed Error In The README.md

xo-install.sh
This commit adds the installation for `libcap2-bin` for Debian systems.
Issue #8 references the issue of `setcap` not existing in Debian by default, and commit 618aeed adds a note that the `libcap2-bin` will be installed, but that commit doesn't add the code to perform the installation.
=> Add setcap installation to Debian

.gitignore, README.md, docker/monit-services, sample.xo-install.cfg, tests/run-tests.sh, xo-install.sh
I realize this is quite a few features bundled into one PR, so let me know if you want me to break this up into a few PRs. Each feature is a separate commit though, so it should be easy to do things one-at-a-time.
[Commit for this feature.](https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/3944e5dabf4d437437f2e31c8cb45fb0ad45f86d)
Right now, if users want to make changes to the default configuration, they must edit `xo-install.sh`. This means that before they pull updates to this repo, they have to stash their changes or commit them and then deal with merges.
This commit removes all of the user-configurable options from `xo-install.sh` and instead sources them from a config file that is not tracked by git (`xo-install.cg`). When a user doesn't have this file (likely the case …
=> Add config file, easy HTTPS setup, faster upgrades, and tagged release upgrades

sample.xo-install.cfg, xo-install.sh
Depending on the situation, a user might have third party plugins that
are needed for their XO setup. We're using a mysql auth plugin, but
github has a handful of other third party plugins.
Added: config setting ADDITIONAL_PLUGINS to specify git repo URLs.
Added: InstallAdditionalXOPlugins function to download/update these
repos and add them to the XO source tree before building.
=> Add ability to install 3rd party plugins

xo-install.sh
the CheckCertificate function fails when using ECC certificates
this change updates the openssl commands that compare certificate and key to ones that are algorithm-generic so that both RSA and ECC (and others?) can be compared and used.
based on answers here: https://security.stackexchange.com/questions/73127/how-can-you-check-if-a-private-key-and-certificate-match-in-openssl-with-ecdsa
and the other linked question: https://security.stackexchange.com/questions/56697/determine-if-private-key-belongs-to-certificate
=> Update to xo-install.sh to allow use of ECC/ECDSA certificates

xo-install.sh
currently the xo-server-test and xo-server-test-plugin can still get linked and throws some errors about said plugins not being built. 
this stops that from happening
=> make sure test modules doesnt get linked

README.md, xo-install.sh
Adds Ubuntu 22.04 to the checks in `xo-install.sh`
Tested locally, appears to be working.
Almalinux 9 might also be worth looking at, I might spin one up later and give `xo-install.sh` a whirl.
=> Add ubuntu 22.04 to the checks

README.md, xo-install.sh
Adds Almalinux 9 to the checks in `xo-install.sh`
Tested locally, appears to be working.
=> Add almalinux 9 to the checks

xo-install.sh
Xen Orchestra redis package nowadays prefers v6 localhost address `::1` when default `localhost` is defined in configuration. Default redis.conf from rpm package doesn't listen v6, but only v4 so xo-server fails to start.
This changes xo-server config to use 127.0.0.1 always. Fixes #135
=> fix: always use v4 localhost connection address for redis

xo-install.sh
this moves the possibly running xo-server/xo-proxy service stop to be done after new build is done to minimize downtime when running update.
=> feat: wait for service shutdown until new build is complete

README.md, xo-install.sh
libxml2 (deb) and libxml2-utils (rpm) was introduced by XO sources requiring it for xmllint which isn't used for source installations
=> chore: remove unused libxml2 pkg

xo-install.sh
Add symlinks for the xo-cli package, which contains the command line API interface to xo.
Install this by symlinking /usr/local/bin/xo-cli as well.
=> xo-cli install

xo-install.sh
While using the interactive prompt to test whether the script will update when there are no updates available, I noticed that selecting anything other than lower-case "n" results in an upgrade taking place.  I think this runs counter to the logic displayed in the rest of the script: that is, if the response is not "y" it should be treated as "n".
This was also annoying because my original response was upper-case "N" (which the prompt requested for "no"), but the upgrade happened anyway.
As an aside, it seems weird that (I think) [this line](https://github.com/ronivay/XenOrchestraInstallerUpdater/blob/70ea9a0509ce35329349a078db56758591b81f67/xo-install.sh#L621) is supposed to convert an empty response to "n", but having a case statement that catches anything with * makes said line …
=> Adding * to catch all other read responses to an unneeded upgrade to NOT continue the upgrade (standardized with the rest of the script).

README.md, xo-install.sh
End of support in 6/2023. node.js 18.x not supported in nodesource repo
"Resolves" issue #168
=> chore: remove ubuntu 18 support

sample.xo-install.cfg, xo-install.sh
Add config option `YARN_CACHE_CLEANUP`. When set to true, will run `yarn cache clean` at the end of an update. Defaults to false.
Resolves #182
=> feat: add automatic yarn cache cleanup with a config option

README.md, xo-install.sh
Debian 12 "Bookworm" has been released and seems from my testing to create no breaking changes for XOIU. I have tested on a fresh Debian 12 installation with the changes included in this pull request and XOIU installs and runs without fault.
=> Support Debian 12 "bookworm"

sample.xo-install.cfg, xo-install.sh
Adds YARN_NETWORK_TIMEOUT configuration variable to set arbitrary timeout value. Defaults to 300seconds
=> feat: add default yarn network-timeout and make it configurable

xo-install.sh
`yum` was deprecated on RHEL8 and since this script only supports EL8 and up it should not use `yum` and just use `dnf` instead.
This is valid for all distros based on EL, like Alma and Rocky.
More information:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#notable-changes-to-the-yum-stack_software-management
=> Use `dnf` instead of `yum` for Enterprise Linux distros

xo-install.sh
bug reported in: #244
`$CONFIGPATH/.config` directory was left owned by root even when running the service as non-root user.
=> fix: non-root user .config directory permissions

xo-install.sh
in some corner cases, the running process check fails. see #253
=> fix: running process check, match only node processes

README.md, xo-install.sh
This is just a workaround for issue #256 to get RHEL installations to go through. This makes them unable to do file level restore from backups until another source for libvhdi-tools package is implemented.
=> fix: workaround for failing rhel installations for now

README.md, xo-install.sh
Add support for:
- AlmaLinux 10
- RockyLinux 10
- Centos Stream 10
redis package has been dropped from repos and replaced with valkey. This PR also includes conditional checks to the installation process to install valkey instead.
=> feat: add support for centos/almalinux/rockylinux 10

xo-install.sh
reported in: https://github.com/ronivay/XenOrchestraInstallerUpdater/issues/305
caused by: https://github.com/ronivay/XenOrchestraInstallerUpdater/pull/304
=> fix: missing redis variable for rhel <10
